language: node_js
node_js:
- 10
cache:
  yarn: true
  directories:
  - node_modules
addons:
  sonarcloud:
    organization: "xyo-network"
install:
- yarn install
script:
- yarn build
- sonar-scanner
env:
  global:
  - secure: tb6oqKMySZCXj8TKqtdzqyQtWb+FYZ4pE3zloqDRIASuCIodwawpwKenLimJFb9ux/c76FkCWgQZxNBvcpkWXHTWTFCPGXIojk+5VoBzFPH437gN2zv9LctjIzuUvq/WLjlhCUqdWfboI3w7XHIYblXmD5f613eJWoY0oyJIXViDpOzFlFsQIV3zy7eCB0m6x4AmJB3CmQdfuzFDqdwx9mT/k1Joa32jUYkP0+F0aH/Z4Lp1Wb/UEXdr8KwOOcPIhXkjV15tJ/Ump47BNFr8sXK2IBdL8bS6WvBc9BugCZP/KWJLlS5NIIlnHmyi9pgHxwqitm5FvcbQlqxErwKAqglEWA0POAi25A/X2ZqPA4mwLq0esHOAM2RgM3acaAjYGDtQETm9dFYoCEj3l/RhhqIJbfzwOPwI+bSOb4bqri+v67Qh10G8Qk2nkNTHFN67DusR18ioXFn4m0sNcZrMXouhoh9OwDEdYwXY5Upl5CBQvg15yDYt7P3yKqUBE5DcPLfrKnK2pq+GwzXlRDoKrtcHWJdSV/pyDPMoP6z6pAIIpixr8T/0zLYOFGzfNBkD/kf2+dvxurSoIqq2rYjpvEgmesvWU3aPxAzeTHTgvMBaXmK4KG2ww+6oI18LGvjKzKC+5QMo2qSOihfhZ9G5VL7oZxbp8JkiVnfR7ZVQ0ug=