language: node_js
node_js:
- 10
cache:
  yarn: true
  directories:
  - node_modules
addons:
  sonarcloud:
    organization: "xyo-network"
install:
- yarn install
script:
- yarn build
- sonar-scanner
env:
  global:
  - secure: k3RnOTyeMy6uoNQHb726qtMWYgcg0rC9nxCPVf7B1+Hwos+i3FAUfrW0J8xGJUjSHi00f1ERvYQtQtYM9/Ug+iiNlk1URssNkTGu4spLKCLNatQvZXZ+WINR+hxGfusXTa40iC1zdWPRIMw9550mV1caE3yMAtoX2nAgIKxtQxuTqO0r5mZryawLKXRUqppQnnHP9jzDXyKs98t9+g4L8mZvoS7Wk2ZcWqROnsH8dMrqzapTWG11k/M5tp0QQwRI0yvq/vSdUOoklCEiBUfbjoVr6RwjxuQ5ywE/fMneEfz9mzUR6jcvqSLlzTAgfoPWU2W5iQGfzf9CqsJ0+rfIflYwM0dBTMe2v/Veq8vZ1dRUojvGY/IQ554jOD6SruBZ8ge7BcEpV/OQGL8X29ttKmnPDwreScbSNbqdrGTVaYwnnkgajg/N6oTc9AMgoh21MvFtuuu8SPTH2b9zUAeYo5iWsa53r0wonDn5G0eULRoAHU60sYJAt+XCSw+oQA9Xb33hT2in1kBUmm7tx2Vutw/SJHXDn/X553A5KjcyXGpwxR/lPKZHDzUN0tUuiJyWTiXpYlMWjUIY0dLIIGCI+Iur2UtmO5k24vZKWnMEpIfYNVKWcRgJkF+8SMwGo/l4GieYt1sN+/3otG6QkHGrKPZBYID4JomaJTKwZuCXlGo=