language: node_js
node_js:
- 10
cache:
  yarn: true
  directories:
  - node_modules
addons:
  sonarcloud:
    organization: xyo-network
install:
- yarn install
script:
- yarn build
- sonar-scanner
env:
  global:
  - secure: K7hg7SEiI+4iloS9Ka/vW8mDk/fygRUvBnWkBByP1Pj0HUDifrJHl3R3cb0hWpriVU3djapdUM87LtqBBX2g1uiFgGVofUohya3sEYeDHSB0XswCbLOMRV/u+zKbIo1zT2EMB26np/qyG91CDaW+83jnBuasNcA62bZ0FlJVW7454T9Whw4tlIWTgM+Va/5FXnCG0FKvajyAwTa2DXCj/Go6iSd6cBezDqmNMDZ9V21SvUhP6g7AjDrLAOzlOVVM43gOUuAxWFVjlsoeZI/z05bg4TpfGzRCCgNGxTXPaGa3LyPJ/mDEPO7DACsZOSnS22zxTSuBkR5qaCL3ogBe6+CiHfNuDy8lHb2hWOwgLnkShEdUcezJVp8ipJwPy/4YIUL6mj4UlJnK8BbfzyAaFPCa6DvQVrU5fQs5F0lp5HNxyORpIU+hyvzsKX4jUC7JFlGCVJzAntNx+gu1Zc5pl+5yREXnYGk2kMghxKwF1iXzYP1mdtgx35712oEO1Rbcov2aqG0tSrPVUVySCm6EeaxRX8KNnrJI50S8C3NYFCLmX8SKly24LsXjiWSO3NagExmaq8OxNvhVFd/mP2yhituUs/H5984yk1Nl+2q+OGOLiIWWHsnStRFXvtD7TyWZbqJ18k9RCQpR4MsubZbDDxZu28d0qHIGZYXeJZPTlmo=
  - secure: js/900pD74YlepNImgan0MmDbe7LePJdxm2ynxXCEvLwP0VcvDbK5Iq/GWHkl1hmgVJs5oT1EcRN8rE1NIcZy8PQY3gf2/sDJOd8QVF3VvCES6hc5U8Jw/4lhoUTrWuCH26uPQ0wHdQsQt9wIKj8b4URZ7L6LU5Ls8fZAnAh78Ja3Z/AJyv/EyQI8D1RZhDbs5drHEDrRtte1+zDz8kagdUL/3im0Ty9xetE/tnMlKlJiQz7x3A1aPGhCcQDEt9bugFhMzX60sa3A679yKPIHcRGN33SEEpJHEvond6km1FBdjRNsFrW195zG5/ivYbQsIr4TtUSYcvk2IidA6EjYSjBuSg2rAetrith0Y1PA1OmWJuPVIdZbc4kPpNGUJdVDawx0HJID+JLn2E3KozP6vKjLoAlNg3IHCsCmtwmuqWUChR+SrAwn8xgQfBoqKJvX3pA5z9EsdUnTfc3un4ph4KdtNh+Uol11BVTTLj71J8PbzoZ4/xFqOJP4vFZGsMRAlUwz9IAy31xEnPvX+5cR3hGTtlBVuMUSLfSA1NkTRRzx3X9G6OqGushANy/N9iL/Oqf6lvwQhgW1hBKxhLl3Q02gbYeRMZpYjJrXbiSymsAGsc6Jok+r+QFANsMvMEalB6Wpw7fumBDUc/VrKfgOgW2MeaUUyrbP+T2eZo6Zgw=
