language: node_js
node_js:
- 10
cache:
  yarn: true
  directories:
  - node_modules
addons:
  sonarcloud:
    organization: "xyo-network"
install:
- yarn install
script:
- yarn build
- sonar-scanner
env:
  global:
  - secure: nWEjqTvymGt+e2/NEgeGZNR+C15VdOkkyt18CVuVeoyMTni8x5gVm3YjVdBorepVSvBSA9ffxRNPdUIM5+EkYMMnhcK3puGEquEyBpLHI+Z4UtMbFxmO+1fm7E0y48ypPejWw++9ZEk0U/H/RooTIMd4B3SwmiH0589Npxdu+LOTeOfbC+Pko0shmNsjjNkvPL2zvbFhvAxrZzlYee4uB9XorG6W6l6+sb0oee3BxqwJGVbNfMyNOMdTBJAVlNVybVSceINPF9FGlEpdHy8RBjF9UFpCXNDyLceMPL/Rd2RC2uP2QtbUvjxy3/Z6RJMxTF7nEXHajJef5pNeWJBUpO8Flhg4NxXBGIE+h+VDk66QcDRGY6N1U5r9ExQ8oijQVV/avScM4wIoYiuif3c1E0mYQsR4NtWn7HsOo/b/R5VsLx7vTzLXVwJm5EF7V08mHzhA301u8xH9S7tUJ/1iWXYXpbzSvhPjEM9Wd8HBKsPIP6nZWTxSiKcXAn1JYDOoqqc9qsyGFj4G1x+swHBTXxtZxhDHE/uXh4c3cW4l0z5HBrX94xaubSSP1gaRE6HhcLduw+J/veq2qGXC1U1kLTXMvbbh/+yztYfkOCRTHSwNvkA8RLtxRof59dKhW86Hb9SIRwIJRoLt36BBrQ8li7RqAkEjvs0EbQlK6wv1AQU=