language: node_js
node_js:
- 10
cache:
  yarn: true
  directories:
  - node_modules
addons:
  sonarcloud:
    organization: "xyo-network"
install:
- yarn install
script:
- yarn build
- sonar-scanner
env:
  global:
  - secure: K7hg7SEiI+4iloS9Ka/vW8mDk/fygRUvBnWkBByP1Pj0HUDifrJHl3R3cb0hWpriVU3djapdUM87LtqBBX2g1uiFgGVofUohya3sEYeDHSB0XswCbLOMRV/u+zKbIo1zT2EMB26np/qyG91CDaW+83jnBuasNcA62bZ0FlJVW7454T9Whw4tlIWTgM+Va/5FXnCG0FKvajyAwTa2DXCj/Go6iSd6cBezDqmNMDZ9V21SvUhP6g7AjDrLAOzlOVVM43gOUuAxWFVjlsoeZI/z05bg4TpfGzRCCgNGxTXPaGa3LyPJ/mDEPO7DACsZOSnS22zxTSuBkR5qaCL3ogBe6+CiHfNuDy8lHb2hWOwgLnkShEdUcezJVp8ipJwPy/4YIUL6mj4UlJnK8BbfzyAaFPCa6DvQVrU5fQs5F0lp5HNxyORpIU+hyvzsKX4jUC7JFlGCVJzAntNx+gu1Zc5pl+5yREXnYGk2kMghxKwF1iXzYP1mdtgx35712oEO1Rbcov2aqG0tSrPVUVySCm6EeaxRX8KNnrJI50S8C3NYFCLmX8SKly24LsXjiWSO3NagExmaq8OxNvhVFd/mP2yhituUs/H5984yk1Nl+2q+OGOLiIWWHsnStRFXvtD7TyWZbqJ18k9RCQpR4MsubZbDDxZu28d0qHIGZYXeJZPTlmo=
  